const {
  REACT_APP_API_PATH = 'http://api.aviationstack.com/v1',
  REACT_APP_FLIGHT_ACCESS_KEY = '8b253cff29429fa3f0b47da75f7a2f0b',
  REACT_APP_AIR_PORT_PUBLIC_KEY = 'dd5ff02bb8',
  REACT_APP_AIR_PORT_SECRET_KEY = '50c8da50b4ab411',
} = process.env;

export const API_PATH = REACT_APP_API_PATH;
export const FLIGHT_ACCESS_KEY = REACT_APP_FLIGHT_ACCESS_KEY;
export const AIR_PORT_PUBLIC_KEY = REACT_APP_AIR_PORT_PUBLIC_KEY;
export const AIR_PORT_SECRET_KEY = REACT_APP_AIR_PORT_SECRET_KEY;
